# Start with a base image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy requirements file
COPY ./requirements.txt /app/requirements.txt

# Install Python dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Set environment variables
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8