name: Python application test with Github Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API Gateway Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:${{ github.sha }} ./src/api/api_gateway/
          docker push rs232gaming/mlops_london_firebrigade:${{ github.sha }}

      - name: Build and push Process Data Service Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:${{ github.sha }} ./src/api/microservices/process_data_service/
          docker push rs232gaming/mlops_london_firebrigade:${{ github.sha }}

      - name: Build and push Build Features Service Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:${{ github.sha }} ./src/api/microservices/build_features_service/
          docker push rs232gaming/mlops_london_firebrigade:${{ github.sha }}

      - name: Build and push Train Model Service Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:${{ github.sha }} ./src/api/microservices/train_model_service/
          docker push rs232gaming/mlops_london_firebrigade:${{ github.sha }}

      - name: Build and push Predict Service Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:${{ github.sha }} ./src/api/microservices/predict_service/
          docker push rs232gaming/mlops_london_firebrigade:${{ github.sha }}

      - name: Build and push MLflow Service Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:${{ github.sha }} ./src/monitoring/mlflow/
          docker push rs232gaming/mlops_london_firebrigade:${{ github.sha }}