name: CD Pipeline to push docker images to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Base Image Docker image
        run: |
          docker build -t myapp/base:latest -f Dockerfile.base .
#         docker build -t myapp/base:${{ github.sha }} -f Dockerfile.base .
#         docker tag myapp/base:${{ github.sha }} myapp/base:latest
#         docker push myapp/base:${{ github.sha }}
#         docker push myapp/base:latest

      - name: Build and push API Gateway Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:api-gateway-${{ github.sha }} -f ./src/api/api_gateway/Dockerfile .
          docker tag rs232gaming/mlops_london_firebrigade:api-gateway-${{ github.sha }} rs232gaming/mlops_london_firebrigade:api-gateway-latest
          docker push rs232gaming/mlops_london_firebrigade:api-gateway-${{ github.sha }}
          docker push rs232gaming/mlops_london_firebrigade:api-gateway-latest

      - name: Build and push Process Data Service Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:process-data-${{ github.sha }} -f ./src/api/microservices/process_data_service/Dockerfile .
          docker tag rs232gaming/mlops_london_firebrigade:process-data-${{ github.sha }} rs232gaming/mlops_london_firebrigade:process-data-latest
          docker push rs232gaming/mlops_london_firebrigade:process-data-${{ github.sha }}
          docker push rs232gaming/mlops_london_firebrigade:process-data-latest

      - name: Build and push Build Features Service Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:build-features-${{ github.sha }} -f ./src/api/microservices/build_features_service/Dockerfile .
          docker tag rs232gaming/mlops_london_firebrigade:build-features-${{ github.sha }} rs232gaming/mlops_london_firebrigade:build-features-latest
          docker push rs232gaming/mlops_london_firebrigade:build-features-${{ github.sha }}
          docker push rs232gaming/mlops_london_firebrigade:build-features-latest

      - name: Build and push Train Model Service Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:train-model-${{ github.sha }} -f ./src/api/microservices/train_model_service/Dockerfile .
          docker tag rs232gaming/mlops_london_firebrigade:train-model-${{ github.sha }} rs232gaming/mlops_london_firebrigade:train-model-latest
          docker push rs232gaming/mlops_london_firebrigade:train-model-${{ github.sha }}
          docker push rs232gaming/mlops_london_firebrigade:train-model-latest

      - name: Build and push Predict Service Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:predict-service-${{ github.sha }} -f ./src/api/microservices/predict_service/Dockerfile .
          docker tag rs232gaming/mlops_london_firebrigade:predict-service-${{ github.sha }} rs232gaming/mlops_london_firebrigade:predict-service-latest
          docker push rs232gaming/mlops_london_firebrigade:predict-service-${{ github.sha }}
          docker push rs232gaming/mlops_london_firebrigade:predict-service-latest

      - name: Build and push MLflow Service Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:mlflow-${{ github.sha }} -f ./src/monitoring/mlflow/Dockerfile .
          docker tag rs232gaming/mlops_london_firebrigade:mlflow-${{ github.sha }} rs232gaming/mlops_london_firebrigade:mlflow-latest
          docker push rs232gaming/mlops_london_firebrigade:mlflow-${{ github.sha }}
          docker push rs232gaming/mlops_london_firebrigade:mlflow-latest