name: CI/CD Pipeline for MLOPS London FIRE Brigade Project

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Dockerfile.base'
      - 'requirements.txt'
      - 'tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Dockerfile.base'
      - 'requirements.txt'
      - 'tests/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
          python -m unittest discover -s tests -v

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Base Image Docker image
        run: |
          docker build -t base:latest -f Dockerfile.base .
      - name: Build and push API Gateway Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:api-gateway-${{ github.sha }} -f ./src/api/api_gateway/Dockerfile .
          docker push rs232gaming/mlops_london_firebrigade:api-gateway-${{ github.sha }}
      - name: Build and push Process Data Service Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:process-data-${{ github.sha }} -f ./src/api/microservices/process_data_service/Dockerfile .
          docker push rs232gaming/mlops_london_firebrigade:process-data-${{ github.sha }}
      - name: Build and push Build Features Service Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:build-features-${{ github.sha }} -f ./src/api/microservices/build_features_service/Dockerfile .
          docker push rs232gaming/mlops_london_firebrigade:build-features-${{ github.sha }}
      - name: Build and push Train Model Service Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:train-model-${{ github.sha }} -f ./src/api/microservices/train_model_service/Dockerfile .
          docker push rs232gaming/mlops_london_firebrigade:train-model-${{ github.sha }}
      - name: Build and push Predict Service Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:predict-service-${{ github.sha }} -f ./src/api/microservices/predict_service/Dockerfile .
          docker push rs232gaming/mlops_london_firebrigade:predict-service-${{ github.sha }}
      - name: Build and push MLflow Service Docker image
        run: |
          docker build -t rs232gaming/mlops_london_firebrigade:mlflow-${{ github.sha }} -f ./src/monitoring/mlflow/Dockerfile .
          docker push rs232gaming/mlops_london_firebrigade:mlflow-${{ github.sha }}