# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
  

      - name: Activate virtualenv
        run: |
            cd ..
            ls -l
            python3 -m venv ./venv
            source venv/bin/activate
            echo PATH=$PATH >> $GITHUB_ENV
        
      # - name: Linters
      #   run: |
      #     sudo apt install pre-commit 
      #     pre-commit
        
      - name: Install dependencies
        run: |
            cd ../mlops_london_firebrigade
            pip install -r requirements.txt
    
      - name: Test with unitest
        run: |
            cd ../mlops_london_firebrigade
            python3 -m http.server
            python3 -m unittest tests.test_api

          # python3 -m unittest tests.test_build_features
          # python3 -m unittest tests.test_data_processing
          # python3 -m unittest tests.test_predict_model
          # python3 -m unittest tests.test_train_model


  docker:
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout
          uses: actions/checkout@v4
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
                    username: oarfani
                    password: dckr_pat_6qz7JclyJHlXizFG7SlYOusi5jY 


                    
        -
          name: Build and push
          uses: docker/build-push-action@v6
          with:
              context: .
              push: true
              tags: user/app:latest